name: beats_infinity
description: "Beats Infinity - Singer group event & pairing manager"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/beats.png

flutter_native_splash:
  color: "#0D0D0D"

  image: assets/images/beats.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#0D0D0D"
    image: assets/images/beats.png

  fullscreen: true